#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
dependencies="$(mktemp)"
trap 'rm -f "$dependencies"' EXIT

cd "$repo_root"
cargo about generate about.hbs >"$dependencies"

{
    printf '%s\n\n' \
        'THIRD-PARTY LICENSES' \
        'This file is generated by scripts/generate-third-party-licenses.sh.' \
        'Do not edit it directly.'

    printf '%s\n' '================================================================================'
    printf '%s\n' 'Font Awesome 7 Free'
    printf '%s\n\n' \
        'Bundled file: assets/fonts/font-awesome/Font Awesome 7 Free-Solid-900.otf'
    cat 'assets/fonts/font-awesome/LICENSE.txt'
    printf '\n\n'

    printf '%s\n' '================================================================================'
    printf '%s\n' 'Inter'
    printf '%s\n\n' 'Bundled file: assets/fonts/inter/InterVariable.ttf'
    cat 'assets/fonts/inter/LICENSE.txt'
    printf '\n\n'

    printf '%s\n' '================================================================================'
    printf '%s\n' 'Kenney Pattern Pack'
    printf '%s\n\n' 'Bundled files: assets/textures/patterns/*.png'
    cat 'assets/textures/patterns/License.txt'
    printf '\n\n'

    printf '%s\n' '================================================================================'
    printf '%s\n\n' 'Rust dependencies'
    cat "$dependencies"
} >THIRD_PARTY_LICENSES.txt
