//! ECS-resident catalog of modifier types the editor knows how to
//! instantiate.
//!
//! Why a registry instead of a hand-maintained enum?
//!
//! - Adding a new modifier is one [`ModifierRegistry::register`] call
//!   instead of touching an enum + four match arms.
//! - The list lives in a [`Resource`], not a static slice, so future
//!   work (user-defined modifiers, plugin-contributed modifiers) just
//!   inserts more entries at runtime — no compile-time enum to grow.
//! - Each entry's [`ModifierContext`] is queried from
//!   `Modifier::context()` at registration time (one throwaway
//!   instance) instead of being declared in parallel with the
//!   factory.
//!
//! What's *intrinsically* per-type is the factory closure that
//! allocates the modifier's `ExprHandle` literals into a
//! [`Module`]: `ExprHandle` is a typeless arena index, so reflection
//! alone cannot pick "Vec3::ZERO for a position field, 1.0 for a
//! radius field". That stays a per-modifier line. Everything else —
//! display name, valid contexts, render-vs-plain discrimination —
//! falls out of the factory's output.

use bevy::math::{Vec3, Vec4};
use bevy::prelude::*;
use bevy_hanabi::{
    AccelModifier, Attribute, LinearDragModifier, Module, ModifierContext, OrientMode,
    OrientModifier, SetAttributeModifier, SetColorModifier, SetPositionSphereModifier,
    SetSizeModifier, SetVelocitySphereModifier, ShapeDimension,
};
use std::borrow::Cow;

use crate::document::ModifierGroup;
use crate::modifier_ops::BoxedAnyModifier;

/// Builds a fresh modifier instance, allocating any required
/// `ExprHandle` literals into `module`.
pub type ModifierFactory = fn(&mut Module) -> BoxedAnyModifier;

/// One registry entry: identifies a modifier type and knows how to
/// construct a default instance.
#[derive(Clone)]
pub struct ModifierKind {
    /// `reflect_short_type_path()` of the underlying Hanabi modifier
    /// struct. Doubles as the lookup key (via
    /// [`crate::ui::modifier_names`]) and the wire identifier carried
    /// inside [`crate::edits::EditKind::AddModifierFromTemplate`].
    pub short_type_name: &'static str,
    /// Default-instance factory.
    pub factory: ModifierFactory,
    /// `Modifier::context()` of an instance built by `factory`, cached
    /// at registration time. Render modifiers always report
    /// [`ModifierContext::Render`].
    pub context: ModifierContext,
}

impl ModifierKind {
    /// User-facing display name (curated table with CamelCase
    /// fallback).
    pub fn display_name(&self) -> Cow<'static, str> {
        crate::ui::modifier_names::display_name_for_type(self.short_type_name)
    }
}

/// Eagerly-populated catalog of every modifier type the editor can
/// add. The source of truth — no parallel static array.
#[derive(Resource, Default)]
pub struct ModifierRegistry {
    entries: Vec<ModifierKind>,
}

impl ModifierRegistry {
    /// Register a modifier type. Builds a throwaway instance in a
    /// scratch [`Module`] to derive its [`ModifierContext`]; the
    /// scratch module is then dropped.
    pub fn register(&mut self, short_type_name: &'static str, factory: ModifierFactory) {
        let mut scratch = Module::default();
        let probe = factory(&mut scratch);
        let context = match &probe {
            BoxedAnyModifier::Plain(m) => m.context(),
            // Render modifiers' context() is generated by
            // `impl_mod_render!` and always returns Render.
            BoxedAnyModifier::Render(_) => ModifierContext::Render,
        };
        self.entries.push(ModifierKind {
            short_type_name,
            factory,
            context,
        });
    }

    /// All registered modifier kinds in registration order. Kept as
    /// part of the public API for future panels that need to list
    /// every modifier (e.g. a type picker for `SetAttributeModifier`'s
    /// attribute field).
    #[allow(dead_code)]
    pub fn iter(&self) -> impl Iterator<Item = &ModifierKind> {
        self.entries.iter()
    }

    /// Entries whose context contains the group's flag. A modifier
    /// valid in multiple contexts (e.g. `SetPositionSphereModifier`
    /// is `Init | Update`) shows up in every matching group's menu.
    pub fn iter_for(&self, group: ModifierGroup) -> impl Iterator<Item = &ModifierKind> {
        let flag: ModifierContext = group.into();
        self.entries.iter().filter(move |k| k.context.contains(flag))
    }

    pub fn get(&self, short_type_name: &str) -> Option<&ModifierKind> {
        self.entries
            .iter()
            .find(|k| k.short_type_name == short_type_name)
    }

    /// Convenience: look up `short_type_name` and call its factory.
    /// `apply_edits` uses [`Self::get`] + `kind.factory` directly to
    /// keep the lookup-failure log message specific; this shortcut
    /// is kept for ad-hoc callers (e.g. tests, future plugins).
    #[allow(dead_code)]
    pub fn make(&self, short_type_name: &str, module: &mut Module) -> Option<BoxedAnyModifier> {
        self.get(short_type_name).map(|k| (k.factory)(module))
    }
}

/// Adds [`ModifierRegistry`] as a resource and populates it with the
/// built-in Hanabi modifiers at startup.
pub struct ModifierRegistryPlugin;

impl Plugin for ModifierRegistryPlugin {
    fn build(&self, app: &mut App) {
        app.init_resource::<ModifierRegistry>()
            .add_systems(PreStartup, populate_builtin_modifiers);
    }
}

/// Adds one entry per built-in Hanabi modifier the editor currently
/// supports. To add a new modifier type, append a single
/// `registry.register(...)` call below.
fn populate_builtin_modifiers(mut registry: ResMut<ModifierRegistry>) {
    // Generic attribute write. The Details panel lets the user pick
    // which attribute and what value once the modifier is in the
    // list. Default: LIFETIME = 5.0 (most commonly the first
    // attribute users want to set).
    registry.register("SetAttributeModifier", |m| {
        let v = m.lit(5.0_f32);
        BoxedAnyModifier::Plain(Box::new(SetAttributeModifier::new(Attribute::LIFETIME, v)))
    });

    registry.register("SetPositionSphereModifier", |m| {
        let center = m.lit(Vec3::ZERO);
        let radius = m.lit(1.0_f32);
        BoxedAnyModifier::Plain(Box::new(SetPositionSphereModifier {
            center,
            radius,
            dimension: ShapeDimension::Volume,
        }))
    });

    registry.register("SetVelocitySphereModifier", |m| {
        let center = m.lit(Vec3::ZERO);
        let speed = m.lit(1.0_f32);
        BoxedAnyModifier::Plain(Box::new(SetVelocitySphereModifier { center, speed }))
    });

    registry.register("AccelModifier", |m| {
        BoxedAnyModifier::Plain(Box::new(AccelModifier::constant(
            m,
            Vec3::new(0.0, -9.81, 0.0),
        )))
    });

    registry.register("LinearDragModifier", |m| {
        BoxedAnyModifier::Plain(Box::new(LinearDragModifier::constant(m, 1.0)))
    });

    registry.register("SetColorModifier", |_m| {
        BoxedAnyModifier::Render(Box::new(SetColorModifier::new(Vec4::new(
            1.0, 1.0, 1.0, 1.0,
        ))))
    });

    registry.register("SetSizeModifier", |_m| {
        BoxedAnyModifier::Render(Box::new(SetSizeModifier {
            size: Vec3::new(0.1, 0.1, 0.1).into(),
        }))
    });

    registry.register("OrientModifier", |_m| {
        BoxedAnyModifier::Render(Box::new(OrientModifier::new(
            OrientMode::ParallelCameraDepthPlane,
        )))
    });
}
